### ISSUE TITLE
README.txt file in plugin folder is not updated

### ISSUE THREAD

**Issue by davemac** [fooplugins/grunt-wp-boilerplate#6]
After running 

`grunt-init wp-boilerplate`

and following the prompts I have my new plugin working, great stuff.

However, it seems the README.txt file in my new plugin is not modified or updated with any of the information I supplied at the prompts. This file still seems to be the default file with helper text etc from wp-boilerplate.

**Comment by bradvin** [comment]
Ye It seems I forgot the readme.txt
It needs the grunt init replacement tags
